#!/usr/bin/env bash
# Install nginx and set the string holberton school in index.html

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.html
service nginx start