#!/usr/bin/env bash
# Install nginx and set the string holberton school in index.html

sudo apt-get update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
sudo echo "Holberton School" > /var/www/html/index.html
service nginx start