#!/usr/bin/env bash
# Install nginx and set the string holberton school in index.html

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
service nginx start
sudo sed -i "26i \\\trewrite ^/redirect_me 9gag.com permanent;" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload