#!/usr/bin/env bash
# Configures an Nginx server so that /redirect_me redirects to another page.

sudo apt-get update
sudo apt-get install -y nginx

sudo touch /etc/nginx/html/index.html
sudo echo "Holberton School" > /etc/nginx/html/index.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 https://9gag.com/;
    }
}" > /etc/nginx/sites-available/default

sudo service nginx restart