#!/usr/bin/env bash
# Install nginx and set the string holberton school in index.html

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
fix="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "26i $fix" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
