#!/usr/bin/env bash
# kills the 7-highlander process instead of the 4-to_infinity_and_beyond one

i=0

while [ $i -eq 0 ]; do
    trap 'echo "I am invincible!!!"' SIGTERM
    echo "To infinity and beyond"
    sleep 2
done