#!/usr/bin/env bash
#print numbers until 100 but
#if i%3 and i%5 print fizzbuzz
#if i%3 print fizz
#if i%5 print buzz
i=1

while [ $i -le 100 ]; do
      if [ $((i%5)) -eq 0 ] && [ $((i%3)) -eq 0 ]; then
	  echo "FizzBuzz"
      elif [ $((i%5)) -eq 0 ]; then
	  echo "Buzz"
      elif [ $((i%3)) -eq 0 ]; then
	  echo "Fizz"
      else
	  echo "$i"
      fi
      i=$((i+1))
done
