#!/usr/bin/env bash
#print "holberton school" 8 times and 
#"bad luck" if position is 4 or "good luck"
#if position is 8
i=0
while [ $i -lt 10 ]; do

	if (( i == 3 )); then
		echo "bad luck"
	elif (( i == 7 )); then
		echo "good luck"
	else
		echo "Holberton School"
	fi

	(( i++ ))

done
