#!/usr/bin/env bash
#give me the our whit 2 while loops
hour=0
while [ "$hour" -le 12 ]; do
	echo "Hour: $hour"
	min=1
	while [ "$min" -lt 60 ]; do
		echo $min
		((min += 1))
	done
	((hour += 1))
done
