#!/usr/bin/env bash
#check a name of a file and show some info
name="holbertonschool"
if [ -f "$name" -o -b "$name" -o -c "$name" -o -d "$name" ]; then
	echo "$name name exists"
	if [ -f "$name" ]; then
		if [ "$(wc -c $name)" != "0" ]; then
			echo "$name is not empty"
		else
			echo "$name is empty"
		fi
		echo "$name is a regular name"
	else
		echo "$name is not empty"
	fi
else
	echo "$name does not exist"
fi
